<?php
/**
 * @var Hust\Service\Block\Locator\View $block
 */
$locator = $block->getLocator();
$serviceId = $block->getServiceId();
$hours = $block->getHours();
?>
<div class="container">
    <div class="title">Chọn thời gian và khung giờ sử dụng dịch vụ</div>
    <div class="info-store">
        <h3>Tên tiệm spa: <?= $locator->getName(); ?></h3>
        <div> ĐỊa chỉ : <?= $locator->getAddress(); ?></div>
        <div>Thành phố : <?= $locator->getCity(); ?></div>
        <div>Số điện thoại : <?= $locator->getPhone(); ?></div>
        <div class="calendar">
            <div class="field">
                <label>Chọn ngày : </label>
                <input type="text" class="input-text" id="example-date" style="width: auto"
                       name="date" data-validate="{required:true, 'validate-date':true}"/>
            </div>
            <div class="select-hour">
                <?php
                foreach ($hours as $key => $hour):
                    ?>
                    <button value="<?= $key ?>" class="o-active"><?= $hour ?></button>
                <?php
                endforeach;
                ?>
            </div>
            <button id="booking" class="booking">Book</button>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#form-booking": {
            "validation": {}
        }
    }
</script>

<style>
    .title {
        text-align: center;
        padding: 15px;
        background-color: #0053a0;
        font-size: 17px;
        color: white;
    }

    div#slot {
        margin-bottom: 10px;
        margin-top: 10px;
    }

    .info-store {
        width: 60%;
        margin: auto;
        line-height: 30px;
    }

    .calendar button {
        margin-left: 20px;
        margin-top: 20px;
    }

    .o-active {
        background-color: #45c3d2;
    }

    .active {
        background-color: #c34706 !important;
    }

</style>

<script>
    require([
        'jquery',
        'mage/translate',
        'mage/calendar'
    ], function ($, $t) {
        $('#example-date').calendar({
            dateFormat: "d/M/yy",
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            currentText: $t('Go Today'),
            closeText: $t('Close'),
            showWeek: true
        });
    })
</script>

<div id="modal-booking-customer" style="display:none;">
    <form class="form form-booking-customer" action="<?php /* @escapeNotVerified */
    echo $block->getUrl('bookings/locator/bookPost') ?>" method="post" id="form-validate" enctype="multipart/form-data"
          data-hasrequired="<?php /* @escapeNotVerified */
          echo __('* Required Fields') ?>" autocomplete="off">
        <h2>Date : <span class="data-date"></span></h2>
        <input type="hidden" name="date"></input>
        <input type="hidden" name="booking_hour"></input>
        <input type="hidden" name="locator_id" value="<?= $locator->getLocatorId();?>"></input>
        <input type="hidden" name="service_id" value="<?= $serviceId;?>"></input>
        <h2>Hour : <span class="data-hour">8h30AM:10AM</span></h2>
        <?php echo $block->getBlockHtml('formkey') ?>
        <div class="field">
            <label class="label">Name</label>
            <div class="control">
                <input type="text" name="name" />
            </div>
        </div>
        <div class="field">
            <label class="label">Age</label>
            <div class="control">
                <input type="text" name="age" />
            </div>
        </div>
        <div class="field">
            <label class="label">Gender</label>
            <div class="control">
                <select name="gender">
                    <option value="1">Male</option>
                    <option value="0">Female</option>
                </select>
            </div>
        </div>
        <div class="field">
            <label class="label">Phone</label>
            <div class="control">
                <input type="text" name="phone">
            </div>
        </div>
        <div class="field">
            <label class="label">Address</label>
            <div class="control">
                <input type="text" name="address" />
            </div>
        </div>
        <div class="field">
            <label class="label">Gmall</label>
            <div class="control">
                <input type="text" name="emall" />
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/modal', 'mage/mage'], function ($, modal) {
        $(document).ready(function () {
            $('#booking').on('click', function () {
                let date = $('#example-date').val();
                console.log("aa" + date);
                $('.data-date').text($('#example-date').val());
                $('.data-hour').text($('button.active').text());
                $('input[name="date"]').val($('#example-date').val());
                $('input[name="booking_hour"]').val($('button.active').val());
                var options = {
                    type: 'popup',
                    modalClass: 'popup-change-profile',
                    title: 'Customer Information',
                    responsive: true,
                    buttons: [
                        {
                            text: 'Cancel',
                            class: 'action modal-cancel',
                            click: function () {
                                this.closeModal();
                            }
                        },
                        {
                            text: 'Submit',
                            class: 'action save primary',
                            click: function () {
                                $('.form.form-booking-customer').submit();
                            }
                        }
                    ]
                };
                var popupAdd = modal(options, $('#modal-booking-customer'));
                $('#modal-booking-customer').modal('openModal');
            })

            $('.select-hour button').on('click', function () {
                $(".select-hour button").each(function () {
                    $(this).removeClass('active');
                });
                $(this).addClass('active');
            })
        });
    })
</script>

