<?php
/**
 * @var Hust\Service\Block\Locator\View $block
 */
$locator = $block->getLocator();
$serviceId = $block->getServiceId();
//$hours = $block->getHours();
$charge = $block->getCharge();
?>
<div class="container">
    <div class="title">Chọn thời gian và khung giờ sử dụng dịch vụ</div>
    <div class="info-store">
        <h3>Tên tiệm spa: <?= $locator->getName(); ?></h3>
        <div> ĐỊa chỉ : <?= $locator->getAddress(); ?></div>
        <div>Thành phố : <?= $locator->getCity(); ?></div>
        <div>Số điện thoại : <?= $locator->getPhone(); ?></div>
        <div class="calendar">
            <input type="hidden" name="locator_id" value="<?= $locator->getLocatorId();?>" />
            <input type="hidden" name="service_id" value="<?= $serviceId;?>" />
            <div class="field">
                <label>Chọn ngày : </label>
                <input type="text" class="input-text" id="example-date" style="width: auto"
                       name="date" data-validate="{required:true, 'validate-date':true}"/>
            </div>
            <div id="slot"></div>
            <h2>Phí dịch vụ ($) : <strong class="charge"><?= $charge?></strong></h2>
            <label>Yêu cầu từ bạn</label>
            <textarea name="require" rows="7"></textarea>
            <div class="voucher-app">
                <label style="margin-right: 30px">Voucher Code</label>
                <div><input type="text" name="voucher_code"></div>
                <div style="background: lightblue" id="apply"><?=__("Apply")?></div>
            </div>
            <p class="note" style="color: red; display: none"></p>
            <button id="booking" class="booking" style="background: bisque;padding: 20px 40px;">Book</button>
        </div>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        "mage/url"
    ], function ($, urlBuilder) {
        $(document).ready(function () {
            $('#example-date').change(function () {
                var url = urlBuilder.build('bookings/locator/slot');
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        service_id: $("input[name='service_id']").val(),
                        locator_id: $("input[name='locator_id']").val(),
                        date: $("input[name='date']").val()
                    },
                    success: function (response) {
                        console.log(response)
                        $('#slot').html(response.slot)
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            });

            $("#apply").click(function () {
                var url2 = urlBuilder.build('bookings/locator/voucher');
                $.ajax({
                    url: url2,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                       code : $("input[name='voucher_code']").val()
                    },
                    success: function (response) {
                        if (response.has) {
                            let voucher = response.code[0];
                            let voucher_id = voucher.voucher_id;
                            let discount = voucher.discount;
                            let charge = <?= $charge?>;
                            var newCharge = parseInt(charge)*(100 - discount)*0.01;
                            console.log("bb",voucher_id);
                            $(".voucher-app").hide();
                            $(".charge").text(newCharge);
                            $("input[name='charge']").val(newCharge);
                            $("input[name='voucher_id']").val(voucher_id);
                            $(".note").text("Voucher thành công");
                            $(".note").show();
                        } else {
                            $(".note").text("Voucher không hợp lệ, vui lòng nhập lại");
                            $(".note").show();
                        }
                        // console.log(response)
                        // $('#slot').html(response.slot)
                    },
                    error: function (xhr, status, errorThrown) {
                        $(".note").text("Bạn vui lòng nhập voucher");
                        $(".note").show();
                    }
                });
            })

        });
    })
</script>

<style>
    .title {
        text-align: center;
        padding: 15px;
        background-color: #0053a0;
        font-size: 17px;
        color: white;
    }

    div#slot {
        margin-bottom: 10px;
        margin-top: 10px;
    }

    .info-store {
        width: 60%;
        margin: auto;
        line-height: 30px;
    }

    .calendar button {
        margin-left: 20px;
        margin-top: 20px;
    }

    .o-active {
        background-color: #45c3d2;
    }

    .active-hour {
        background-color: #c34706 !important;
    }

    .voucher-app {
        display: flex;
    }
    div#apply {
        margin-left: 30px;
        padding: 5px 10px;
        cursor: pointer;
    }

</style>

<script>
    require([
        'jquery',
        'mage/translate',
        'mage/calendar'
    ], function ($, $t) {
        $('#example-date').calendar({
            dateFormat: "y-m-d",
            timeFormat: "HH:mm:ss",
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            currentText: $t('Go Today'),
            closeText: $t('Close'),
            minDate: new Date(),
            maxDate : (new Date()).getDate() + 20
        });
    })
</script>

<div id="modal-booking-customer" style="display:none;">
    <form class="form form-booking-customer" action="<?php /* @escapeNotVerified */
    echo $block->getUrl('bookings/locator/bookPost') ?>" method="post" id="form-validate" enctype="multipart/form-data"
          data-hasrequired="<?php /* @escapeNotVerified */
          echo __('* Required Fields') ?>" autocomplete="off">
        <h2>Date : <span class="data-date"></span></h2>
        <input type="hidden" name="date" />
        <input type="hidden" name="booking_hour" />
        <input type="hidden" name="require" />
        <input type="hidden" name="locator_id" value="<?= $locator->getLocatorId();?>" />
        <input type="hidden" name="service_id" value="<?= $serviceId;?>" />
        <input type="hidden" name="charge" value="<?= $charge;?>" />
        <input type="hidden" name="voucher_id" value="0"/>

        <h2>Hour : <span class="data-hour">8h30AM:10AM</span></h2>
        <?php echo $block->getBlockHtml('formkey') ?>
        <div class="field">
            <label class="label">Name</label>
            <div class="control">
                <input type="text" name="name" data-validate='{"required":true}'/>
            </div>
        </div>
        <div class="field">
            <label class="label">Age</label>
            <div class="control">
                <input type="text" name="age" data-validate='{"required":true}'/>
            </div>
        </div>
        <div class="field">
            <label class="label">Gender</label>
            <div class="control">
                <select name="gender">
                    <option value="1">Male</option>
                    <option value="0">Female</option>
                </select>
            </div>
        </div>
        <div class="field">
            <label class="label">Phone</label>
            <div class="control">
                <input type="text" name="phone" data-validate='{"required":true}'>
            </div>
        </div>
        <div class="field">
            <label class="label">Address</label>
            <div class="control">
                <input type="text" name="address" data-validate='{"required":true}'/>
            </div>
        </div>
        <div class="field">
            <label class="label">Email</label>
            <div class="control">
                <input type="text" name="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        }
    }
</script>

<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/modal', 'mage/mage'], function ($, modal) {
        $(document).ready(function () {
            $('#booking').on('click', function () {
                let date = $('#example-date').val();
                if (date == "") {
                    alert("Bạn chưa chọn ngày");
                    return;
                }
                let hour = $('button.active-hour h2').text();
                if (hour == "") {
                    alert("Bạn chưa chọn khung giờ");
                    return;
                }
                console.log("aa" + date);
                console.log("aa" + hour);
                $('.data-date').text($('#example-date').val());
                $('.data-hour').text($('button.active-hour h2').text());
                $('input[name="date"]').val($('#example-date').val());
                $('input[name="booking_hour"]').val($('button.active-hour').val());
                $('input[name="require"]').val($('textarea').val());
                var options = {
                    type: 'popup',
                    modalClass: 'popup-change-profile',
                    title: 'Customer Information',
                    responsive: true,
                    buttons: [
                        {
                            text: 'Cancel',
                            class: 'action modal-cancel',
                            click: function () {
                                this.closeModal();
                            }
                        },
                        {
                            text: 'Submit',
                            class: 'action save primary',
                            click: function () {
                                $('.form.form-booking-customer').submit();
                            }
                        }
                    ]
                };
                var popupAdd = modal(options, $('#modal-booking-customer'));
                $('#modal-booking-customer').modal('openModal');
            })

            $('.select-hour button').on('click', function () {
                $(".select-hour button").each(function () {
                    $(this).removeClass('active-hour');
                });
                $(this).addClass('active-hour');
            })
        });
    })
</script>

