<?php
      $calendars = $block->getCalendar();
      $hours = $block->getHourOption();
?>
<div class="caledar">
    <table id="customers">
        <tr>
            <th>Date booking</th>
            <th>Service</th>
            <th>Locator</th>
            <th>phone number</th>
            <th>Address</th>
            <th>Date spa</th>
            <th>Status</th>
        </tr>
        <?php foreach ($calendars as $calendar):?>
            <?php
                   $service = $block->getService($calendar->getServiceId());
                   $locator = $block->getLocator($calendar->getLocatorId());
            ?>
        <tr>
            <td><?=$calendar->getCreatedDatetime();?></td>
            <td><?= $service->getName();?></td>
            <td><?= $locator->getName();?></td>
            <td><?= $locator->getPhone();?></td>
            <td><?= $locator->getAddress()." ".$locator->getCity()." ".$locator->getCountry();?></td>
            <td><?php
                foreach ($hours as $hour) {
                    if ($hour['value'] == $calendar->getBookingStatus()) {
                        echo $hour['label'];
                        break;
                    }
                }
                ?>
                <br>
               <?= $calendar->getDate()?>
            </td>
            <td>
                <?php
                switch($calendar->getBookingStatus()) {
                    case 0:
                        echo 'Waiting';
                        break;
                    case 1:
                        echo 'Accept';
                        break;
                    case 2:
                        echo 'Cancel';
                        break;
                    case 3:
                        echo 'Success';
                        break;
                }
                ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<style>
    #customers {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #customers td, #customers th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    #customers tr:nth-child(even){background-color: #f2f2f2;}

    #customers tr:hover {background-color: #ddd;}

    #customers th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #04AA6D;
        color: white;
    }
</style>
