<?php
$promotions = $block->getAllPromotion();
$a = 1;
?>
<?php if ($promotions):?>
<div class="carousel-wrap">
    <div class="owl-carousel">
        <?php foreach ($promotions as $promotion ):?>
            <a href="<?= $block->getUrl('bookings/promotion/index/promotion_id/'.$promotion['promotion_id']);?>"><div class="item"><img src="<?= $block->getUrl().'pub/media/hust/service/'.$promotion['image'];?>"/></div></a>
        <?php endforeach;?>
    </div>
</div>
<?php endif;?>


<script>
    require(['jquery', 'owlcarousel'], function($) {
        $(document).ready(function() {
            $('.owl-carousel').owlCarousel({
                loop: false,
                margin: 10,
                nav: true,
                navText: [
                    "<i class='fa fa-caret-left'></i>",
                    "<i class='fa fa-caret-right'></i>"
                ],
                autoplay: true,
                autoplayHoverPause: true,
                responsive: {
                    // 0: {
                    //     items: 1
                    // },
                    600: {
                        items: 2
                    },
                    1000: {
                        items: 1
                    }
                }
            });
        });
    });
</script>
