<?php
//$hours = $block->getHourOption();
$slots = $block->getSlot();
?>
<div class="select-hour">
    <?php
    foreach ($slots as $key => $value):
        ?>
        <button value="<?= $key ?>"
                <?php if ($value['slot'] >= 1): ?>
                class="o-active"
                <?php endif; ?>
                >
           <h2><?= $value['value'] ?></h2>
            <?php
               if ($value['slot'] >= 1) {
                   echo '<h3>Available('.$value['slot'].' slot)</h3>';
               } else {
                   echo '<h3>Not Available</h3>';
               }
            ?>
        </button>
    <?php
    endforeach;
    ?>
</div>

<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/modal', 'mage/mage'], function ($, modal) {
        $(document).ready(function () {

            $('.select-hour button.o-active').on('click', function () {
                $(".select-hour button").each(function () {
                    $(this).removeClass('active-hour');
                });
                $(this).addClass('active-hour');
            })
        });
    })
</script>


