<?php
/** @var \Hust\Service\Block\ListServices $block */

$data = $block->getAllService();
?>

<?php if ($data) : ?>
    <div class="immu-cate">
        <?php foreach ($data as $key => $value) : ?>
            <div class="immu-col">
                <h1 class="imu-title"><?php echo __($value['title']); ?></h1>
                <div class="imu-content">
                    <div class="imu-img"><img src="<?php echo __($value['image']); ?>" alt=""></div>
                    <div class="imu-content-child">
                        <div class="imu-content-text">
                            <?php echo __($value['short_description']); ?>
                        </div>
                        <p>Chi phí : <?= $value['price'];?> $</p>
                        <a class="primary imu-content-btn" href="<?php echo __($value['url']); ?>"><?php echo __("BOOK NOW"); ?></a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
