<?php
/** @var \Hust\Service\Block\Service\View $block */
$data = $block->getContentService();
?>

<div class="immu-cate">
    <div class="immu-col">
        <h1 class="imu-title"><?php echo __($data['title']); ?></h1>
        <div class="imu-content-text-detail">
            <?php echo __($data['content']); ?>
        </div>
    </div>
    <?php if ($data['point'] != 0):?>
    <h2><?= __("Review")?></h2>
    <div id="rating">
        <input type="radio" id="star5" name="rating" value="5"/>
        <label class="full" for="star5" title="Awesome - 5 stars"></label>

        <input type="radio" id="star4" name="rating" value="4"/>
        <label class="full" for="star4" title="Pretty good - 4 stars"></label>

        <input type="radio" id="star3" name="rating" value="3"/>
        <label class="full" for="star3" title="Meh - 3 stars"></label>

        <input type="radio" id="star2" name="rating" value="2"/>
        <label class="full" for="star2" title="Kinda bad - 2 stars"></label>

        <input type="radio" id="star1" name="rating" value="1"/>
        <label class="full" for="star1" title="Sucks big time - 1 star"></label>
        <strong style="color: red; font-size: 15px">Point : <?= $data['point']?>/5</strong>
        <?php endif; ?>
    </div>

    <div class="immu-col">
        <h1 class="imu-title"><?php echo __("Danh sách các spa có dịch vụ trên"); ?></h1>
        <div id="click-and-collect" class="click-and-collect">
            <div id="block-click-and-collect" class="content" data-role="content" aria-labelledby="click-and-collect-heading">
           <button id="btn-search">Click vào đây để tìm kiếm</button>
            <div id="stores" class="stores" >&nbsp;</div>
        </div>
        </div>
    </div>

</div>

<script type="text/javascript">
    require([
        'jquery',
        "mage/url"
    ], function ($, urlBuilder) {
        $(document).ready(function () {
            $('#btn-search').click(function(){
                var url = urlBuilder.build('bookings/locator/find');
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                      service_id: <?= $data['service_id']?>
                    },
                    success: function(response) {
                        $('#btn-search').hide();
                        $('#stores').html(response.stores)
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            });
            let point = <?= (int)$data['point']; ?>;
            $( "input[type=radio]" ).each(function() {
                $(this).attr("disabled",true);
                if ($(this).val() == point) {
                    $(this).attr("checked", true)
                }
            });

        });
    })
</script>
<style>
    /*.action.primary, .action-primary {*/
    /*    background-color: white!important;*/
    /*}*/
    .click-and-collect #block-click-and-collect .stores .warehouse {
        padding: 15px;
        border: 1px solid #014c9d;
        border-radius: 0;
        box-shadow: rgba(149,157,165,0.2) 0px 8px 24px;
        line-height: 25px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info {
        font-weight: 700;
    }

    .click-and-collect .warehouse {
        margin-top: 10px;
        color: #282828;
        position: relative;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-name .status.success:before {
        content: '\f00c';
        font-family: 'Font Awesome 5 Pro';
        color: #3e7f16;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 10px;
        font-size: 16px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-name .store-title {
        font-size: 16px;
    }

    .click-and-collect .store-distance {
        color: #ec0f23;
        font-size: 22px;
        float: right;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-available {
        margin-left: 35px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-available .available {
        color: #3e7f16;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-address .address {
        display: flex;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-address .address:before {
        content: '\f3c5';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 6px;
        font-size: 18px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-address .address .full-address {
        margin-left: 4px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-phone .view-store-phone:before {
        content: '\f095';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 7px;
        font-size: 16px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-email .view-store-email:before {
        content: '\f0e0';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 7px;
        font-size: 16px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-hours .view-store-hours:before {
        content: '\f494';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 9px;
        font-size: 14px;
    }

    .click-and-collect .store-actions {
        position: absolute;
        top: 130px;
        right: 15px;
        transform: translateY(-50%);
    }


    .click-and-collect .store-actions button.action:hover a, button.action.primary:hover a, button.action.secondary:hover a{
        background: #014c9d!important;
        color: #ffffff;
        text-decoration: none;
    }

    .click-and-collect .store-actions button.action a{
        color: #014c9d;
    }
    .imu-content-text-detail p {
        line-height: 1.42857143;
    }
    .warehouse-show-more {
        margin-top: 10px;
        margin-left: 0;
        margin-right: 0;
        text-align: center;
    }
</style>

<style>
    div, label {
        margin: 0;
        padding: 0;
    }

    body {
        margin: 20px;
    }

    h1 {
        font-size: 1.5em;
        margin: 10px;
    }

    /****** Style Star Rating Widget *****/
    #rating {
        border: none;
        float: left;
    }

    #rating > input {
        display: none;
    }

    /*ẩn input radio - vì chúng ta đã có label là GUI*/
    #rating > label:before {
        margin: 5px;
        font-size: 2em;
        font-family: FontAwesome;
        display: inline-block;
        content: "\f005";
    }

    /*1 ngôi sao*/
    #rating > .half:before {
        content: "\f089";
        position: absolute;
    }

    /*0.5 ngôi sao*/
    #rating > label {
        color: #ddd;
        float: right;
    }

    /*float:right để lật ngược các ngôi sao lại đúng theo thứ tự trong thực tế*/
    /*thêm màu cho sao đã chọn và các ngôi sao phía trước*/
    #rating > input:checked ~ label,
    #rating:not(:checked) > label:hover,
    #rating:not(:checked) > label:hover ~ label {
        color: #FFD700;
    }

    /* Hover vào các sao phía trước ngôi sao đã chọn*/
    #rating > input:checked + label:hover,
    #rating > input:checked ~ label:hover,
    #rating > label:hover ~ input:checked ~ label,
    #rating > input:checked ~ label:hover ~ label {
        color: #FFED85;
    }
    /*.submit {*/
    /*    position: absolute;*/
    /*    top : 55px;*/
    /*}*/
    /*.rating-x {*/
    /*    display: flex;*/
    /*    flex-direction: column;*/
    /*}*/
</style>
