<?php
/** @var \Dco\Service\Block\Service\View $block */
$data = $block->getContentService();
?>

<div class="immu-cate">
    <div class="immu-col">
        <h1 class="imu-title"><?php echo __($data['title']); ?></h1>
        <div class="imu-content-text-detail">
            <?php echo __($data['content']); ?>
        </div>
    </div>

    <div class="immu-col">
        <h1 class="imu-title"><?php echo __("Danh sách các spa có dịch vụ trên"); ?></h1>
        <div id="click-and-collect" class="click-and-collect">
            <div id="block-click-and-collect" class="content" data-role="content" aria-labelledby="click-and-collect-heading">
           <button id="btn-search">Click vào đây để tìm kiếm</button>
            <div id="stores" class="stores" >&nbsp;</div>
        </div>
        </div>
    </div>

</div>

<script type="text/javascript">
    require([
        'jquery',
        "mage/url"
    ], function ($, urlBuilder) {
        $(document).ready(function () {
            $('#btn-search').click(function(){
                var url = urlBuilder.build('bookings/locator/find');
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                      service_id: <?= $data['service_id']?>
                    },
                    success: function(response) {
                        $('#btn-search').hide();
                        $('#stores').html(response.stores)
                    },
                    error: function (xhr, status, errorThrown) {
                        console.log('Error happens. Try again.');
                    }
                });
            });
        });
    })
</script>
<style>
    /*.action.primary, .action-primary {*/
    /*    background-color: white!important;*/
    /*}*/
    .click-and-collect #block-click-and-collect .stores .warehouse {
        padding: 15px;
        border: 1px solid #014c9d;
        border-radius: 0;
        box-shadow: rgba(149,157,165,0.2) 0px 8px 24px;
        line-height: 25px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info {
        font-weight: 700;
    }

    .click-and-collect .warehouse {
        margin-top: 10px;
        color: #282828;
        position: relative;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-name .status.success:before {
        content: '\f00c';
        font-family: 'Font Awesome 5 Pro';
        color: #3e7f16;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 10px;
        font-size: 16px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-name .store-title {
        font-size: 16px;
    }

    .click-and-collect .store-distance {
        color: #ec0f23;
        font-size: 22px;
        float: right;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-available {
        margin-left: 35px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-info .store-available .available {
        color: #3e7f16;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-address .address {
        display: flex;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-address .address:before {
        content: '\f3c5';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 6px;
        font-size: 18px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-address .address .full-address {
        margin-left: 4px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-phone .view-store-phone:before {
        content: '\f095';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 7px;
        font-size: 16px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-email .view-store-email:before {
        content: '\f0e0';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 7px;
        font-size: 16px;
    }

    .click-and-collect #block-click-and-collect .stores .warehouse .store-hours .view-store-hours:before {
        content: '\f494';
        font-family: 'Font Awesome 5 Pro';
        color: #333;
        width: 25px;
        height: 25px;
        display: inline-block;
        margin-right: 9px;
        font-size: 14px;
    }

    .click-and-collect .store-actions {
        position: absolute;
        top: 130px;
        right: 15px;
        transform: translateY(-50%);
    }


    .click-and-collect .store-actions button.action:hover a, button.action.primary:hover a, button.action.secondary:hover a{
        background: #014c9d!important;
        color: #ffffff;
        text-decoration: none;
    }

    .click-and-collect .store-actions button.action a{
        color: #014c9d;
    }
    .imu-content-text-detail p {
        line-height: 1.42857143;
    }
    .warehouse-show-more {
        margin-top: 10px;
        margin-left: 0;
        margin-right: 0;
        text-align: center;
    }
</style>
