<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>

<!-- set data in js window variable, used in navigation.js file -->
<script>

    window.notificationConfig = <?= /* @escapeNotVerified */ \Zend_Json::encode($block->getNotificationConfig()); ?>;
</script>
<!-- include js file defined in default.xml -->
<div id="notification-component" data-bind="scope:'notification-content'" class="field">
    <script type="text/x-magento-init">
    {
        "#notification-component": {
            "Magento_Ui/js/core/app":  <?= /* @escapeNotVerified */ $block->getJsLayout();?>
        }
    }
    </script>
</div>
<!-- notification template called in navigation.js file -->
<script id="wk_notification_template" type="text/x-magento-template">
    <div class="wk-notification-block">
        <a href="" class="wk-notifications-action marketplace-dropdown">
            <img class="wk-notification-img" height="20" width="20" src="<%- data.notificationImage %>" />
            <% if (data.notificationCount > 5) { %>
            <span class="wk-notification-count">5+</span>
            <% } else { %>
            <span class="wk-notification-count"><%- data.notificationCount %></span>
            <% } %>
        </a>
    </div>
</script>
