<?php
/** @var \Hust\Service\Block\ListServices $block */

$data = $block->getAllService();
?>
<div class="section-title">
    <span><i>Service</i></span>
</div>
<?php if ($data): ?>
    <div class="carousel-wrap">
        <div class="owl-carousel-service">
            <?php foreach ($data as $d): ?>
            <div style="width: 200px;height: 300px">
                <a href="<?= $d['url'] ?>">
                    <div class="item"><img src="<?= $d['image']; ?>" /></div>
                </a>
                <h2><?= $d['title']?></h2>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    require(['jquery', 'owlcarousel'], function ($) {
        $(document).ready(function () {
            $('.owl-carousel-service').owlCarousel({
                loop: true,
                margin: 30,
                nav: true,
                navText: [
                    "<i class='fa fa-caret-left'></i>",
                    "<i class='fa fa-caret-right'></i>"
                ],
                autoplay: true,
                autoplayHoverPause: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    1000: {
                        items: 5
                    }
                }
            });
        });
    });
</script>

