
<table>
    <tr>
        <td>Ngày : <?= date('d-m-Y') ?></td>
        <td style="width: 40%"></td>
        <td><img width="200px" src="<?= $block->getBaseUrl()."pub/media/logo/stores/1/images.png"?>" alt=""></td>
    </tr>
    <tr>
        <td style="width: 25%"></td>
        <td style="width: 50%"><h1>HÓA ĐƠN DỊCH VỤ</h1></td>
        <td style="width: 25%"></td>
    </tr>
    <tr>
        <td>ĐỊA CHỈ : </td>
        <td><?= $block->getAddressLocator($bookingId)?></td>
    </tr>
    <tr>
        <td>SĐT : </td>
        <td><?= $block->getPhoneLocator($bookingId)?></td>
    </tr>
    <tr>
        <td>EMAIL : </td>
        <td><?= $block->getEmailLocator($bookingId)?></td>
    </tr>
    <tr>
        <td>KHÁCH HÀNG : </td>
        <td><?= $block->getName($bookingId)?></td>
    </tr>
    <tr>
        <td>ĐỊA CHỈ : </td>
        <td><?= $block->getAddress($bookingId)?></td>
    </tr>
    <tr>
        <td>SĐT : </td>
        <td><?= $block->getPhone($bookingId)?></td>
    </tr>
</table>
<br>
<br>
<table class="xxx" style="width: 100%">
    <tr>
        <th>STT</th>
        <th>Tên dịch vụ</th>
        <th>Số lượng</th>
        <th>Đơn giá</th>
        <th>Thành tiền</th>
    </tr>
    <tr>
        <td style="text-align: center">1</td>
        <td style="text-align: center"><?= $block->getNameService($bookingId)?></td>
        <td style="text-align: center">1</td>
        <td style="text-align: center"><?= $block->getCharge($bookingId)?></td>
        <td style="text-align: center"><?= $block->getCharge($bookingId)?></td>
    </tr>

</table>
<br>
<table>
    <tr>
        <td style="width: 10%"></td>
        <td style="width: 20%;">Nhân viên</td>
        <td style="width: 50%;"></td>
        <td style="width: 20%">Khách hàng</td>
    </tr>
</table>





<style>
    .xxx, .xxx tr, .xxx th, .xxx td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>
