<?php
$existWarehouses = $block->getExistsLocator();
$countExistWarehouses = $existWarehouses ? count($existWarehouses) : 0;

?>
<?php if ($existWarehouses): ?>
    <?php foreach ($existWarehouses as $warehouse): ?>
        <div class="warehouse">
            <div class="store-info">
                <div class="store-name">
                    <span id="store-status" class="status success"></span><span id="store-title" class="store-title">
                                <?= __($warehouse['name']) ?>
                            </span>
                </div>
            </div>
            <div class="store-address">
                <div class="address">
                    <div class="full-address">
                        <?= __($warehouse['address']) ?> <br>
                        <?= __($warehouse['city']) ?><br>
                    </div>
                </div>
            </div>
            <div class="store-phone">
                <div class="view-store-phone">
                    <?= __($warehouse['phone']) ?>
                </div>
            </div>
            <div class="store-email">
                <div class="view-store-email">
                    <?= __($warehouse['email']) ?>
                </div>
            </div>
            <div class="store-actions">
                    <button class="set-as-my-store action primary" data-store-id="<?php echo $warehouse['locator_id']; ?>" type="button">
                            <span class="set-as-my-store-label">
                                <a class="store-id-<?= $warehouse['locator_id'] ?>" href="<?= $block->getBaseUrl() . 'bookings/locator/booking/id/'. $warehouse['locator_id'].'/service/'. $block->getService() ?>" target="_blank">
                                    <?= __('Book Now') ?>
                                </a>
                            </span>
                    </button>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<?php //if ($countExistWarehouses > 5): ?>
<!--    <div class="warehouse-show-more">-->
<!--        <input type="hidden" id="shows_val" value="5" />-->
<!--        <button class="btn-show-more action primary" type="button">-->
<!--            <span>--><?//= __('Show More') ?><!--</span>-->
<!--        </button>-->
<!--    </div>-->
<?php //endif; ?>


